version = 1
SPDX-PackageName = "OpenCON"
SPDX-PackageSupplier = "DigitalCUBE <info@digitalcube.rs>"
SPDX-PackageDownloadLocation = "https://m.opencon.dev/"

[[annotations]]
path = ["public/**","src/**",".editorconfig", "README.md", "REUSE.toml", "angular.json", "proxy.conf.sample.json", "server.ts", "*.json"]

precedence = "aggregate"
SPDX-FileCopyrightText = "2023 DigitalCUBE <info@digitalcube.rs>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [".github/**", "infrastructure/**", ".gitignore", ".env.example", "calls.http"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
